### ISSUE TITLE
코드 수정 요청 사항

### ISSUE THREAD

**Issue by snoopspy** [qoqokim/add_nbo#1]
https://github.com/qoqokim/add_nbo/commit/3ecc5f9b98fde33ca0e4117990c0c4fa1f25a5f3#r38122578

https://github.com/qoqokim/add_nbo/commit/3ecc5f9b98fde33ca0e4117990c0c4fa1f25a5f3#r38122545

https://github.com/qoqokim/add_nbo/commit/3ecc5f9b98fde33ca0e4117990c0c4fa1f25a5f3#r38122555

https://github.com/qoqokim/add_nbo/commit/01d6a09c71eee76e2003b21a9a9b34c76550055c#commitcomment-38122534

**Comment by qoqokim** [comment]
3월 30일까지 수정하겠습니다.

**Comment by qoqokim** [comment]
done in https://github.com/qoqokim/add_nbo/blob/master/add_nbo.cpp
